export const SECONDS_PER_HOUR = 3600;
export const HOURS_PER_DAY = 24;
export const SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY;
export const SKIP_THRESHOLD_SECONDS = 4 * SECONDS_PER_HOUR;
export const PHASE_LENGTH_SECONDS = 2 * SECONDS_PER_DAY;
